Update README.md and GitHub actions

diff --git a/.github/workflows/master_linters.yml b/.github/workflows/master_linters.yml
--- a/.github/workflows/master_linters.yml
+++ b/.github/workflows/master_linters.yml
@@ -8,7 +8,7 @@ jobs:
     runs-on: ubuntu-latest
     strategy:
       matrix:
-        python-version: ["3.9", "3.10", "3.11", "3.12"]
+        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]
     steps:
     - name: Checkout
       uses: actions/checkout@v4
@@ -29,24 +29,60 @@ jobs:
     - name: Analysing the code with pylint
       id: pylint
       continue-on-error: true
-      run: PYTHONPATH=. pylint $(find . -name '*.py')
+      run: |
+        changed_files=$(git diff --diff-filter=d --name-only $(git merge-base HEAD origin/master) HEAD | grep '\.py$') || true
+        echo $changed_files
+        if [ -n "$changed_files" ]; then
+            PYTHONPATH=. pylint $changed_files
+        else
+            echo "No files changed, passing by"
+            exit 0
+        fi
     - name: Analysing the code with mypy
       id: mypy
       continue-on-error: true
       run: |
-        mkdir -p .mypy_cache
-        PYTHONPATH=. mypy $(find . -name '*.py') --install-types --non-interactive --ignore-missing-imports --exclude __main__.py
+        changed_files=$(git diff --diff-filter=d --name-only $(git merge-base HEAD origin/master) HEAD | grep '\.py$') || true
+        if [ -n "$changed_files" ]; then
+            mkdir -p .mypy_cache
+            PYTHONPATH=. mypy $changed_files --install-types --non-interactive --ignore-missing-imports --exclude __main__.py
+        else
+            echo "No files changed, passing by"
+            exit 0
+        fi
     - name: Check code with flake8
       id: flake8
       continue-on-error: true
-      run: PYTHONPATH=. flake8 $(find . -name '*.py')
+      run: |
+        changed_files=$(git diff --diff-filter=d --name-only $(git merge-base HEAD origin/master) HEAD | grep '\.py$') || true
+        if [ -n "$changed_files" ]; then
+            PYTHONPATH=. flake8 $changed_files
+        else
+            echo "No files changed, passing by"
+            exit 0
+        fi
     - name: Check code with Black
       id: black
       continue-on-error: true
-      run: PYTHONPATH=. black --diff --check --color $(find . -name '*.py')
+      run: |
+        changed_files=$(git diff --diff-filter=d --name-only $(git merge-base HEAD origin/master) HEAD | grep '\.py$') || true
+        echo $changed_files
+        if [ -n "$changed_files" ]; then
+            PYTHONPATH=. black --diff --check --color $changed_files
+        else
+            echo "No files changed, passing by"
+            exit 0
+        fi
     - name: Check runner state
       run: |
-        if [[ "${{ steps.pylint.outcome }}" == "failure" || "${{ steps.black.outcome }}" == "failure" || "${{ steps.mypy.outcome }}" == "failure" ]]; then
-          echo "Linters failed, refer to related sections for info"
+        failed_steps=()
+        if [[ "${{ steps.pylint.outcome }}" == "failure" ]]; then failed_steps+=("Pylint"); fi
+        if [[ "${{ steps.black.outcome }}" == "failure" ]]; then failed_steps+=("Black"); fi
+        if [[ "${{ steps.mypy.outcome }}" == "failure" ]]; then failed_steps+=("Mypy"); fi
+
+        if [ ${#failed_steps[@]} -ne 0 ]; then
+          echo "Failed: ${failed_steps[*]}"
           exit 1
+        else
+          echo "All passed, well done, bro!"
         fi
